# This file was generated by GoReleaser. DO NOT EDIT.
cask "digestive" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "6bc04a495ac4cd903b2dacd03dbdd90ea3b12f74dd387907af3a079eedb97d76"
      url "https://github.com/social-sync/digestive/releases/download/v#{version}/digestive_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "03d73f111588c89c470bc210ebdb4fa47d33665b379546817d8f1fe414dde794"
      url "https://github.com/social-sync/digestive/releases/download/v#{version}/digestive_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cccbaa08193a55f56be2f8307142c3acd9166daff1a642ff4ef0a60f38f11495"
      url "https://github.com/social-sync/digestive/releases/download/v#{version}/digestive_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c44aa903121e0f60d1804b317fd21ceb2eaaced800aa7f37a21b65ca6bda6a54"
      url "https://github.com/social-sync/digestive/releases/download/v#{version}/digestive_#{version}_linux_arm64.tar.gz"
    end
  end

  name "digestive"
  desc "Single-binary database exporter with anonymisation"
  homepage "https://github.com/social-sync/digestive"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "digestive"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/digestive"]
    end
  end

  # No zap stanza required

end
