# This file was generated by GoReleaser. DO NOT EDIT.
cask "digestive" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "74fc220b6e8e0e6d365a4b6d3a95c10f953afddcabb537e9dbbc6db518f3c30a"
      url "https://github.com/social-sync/digestive/releases/download/v#{version}/digestive_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "398be0f79dc8acad9c4ec80d325cbaba32f0868f12cf05e474a7d4521ede1a82"
      url "https://github.com/social-sync/digestive/releases/download/v#{version}/digestive_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "05df70d48eb7141bd38b366efa445adf0ba05977807c573a85d390849bb9d94e"
      url "https://github.com/social-sync/digestive/releases/download/v#{version}/digestive_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a94fa01bf4842ab5a1bea81e8d9d0347ff4e205a913429ff18883df4059f2009"
      url "https://github.com/social-sync/digestive/releases/download/v#{version}/digestive_#{version}_linux_arm64.tar.gz"
    end
  end

  name "digestive"
  desc "Single-binary database exporter with anonymisation"
  homepage "https://github.com/social-sync/digestive"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "digestive"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/digestive"]
    end
  end

  # No zap stanza required

end
