# This file was generated by GoReleaser. DO NOT EDIT.
cask "digestive" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "950e5c32c4eac27c4f2050c977c5a4f521b8aa33751c6e50bfc3fc3a555dbb82"
      url "https://github.com/social-sync/digestive/releases/download/v#{version}/digestive_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f96540ec86cbc4cbdd1d9b0f8d63299b676d753961c3970c3d5bcb68e926a875"
      url "https://github.com/social-sync/digestive/releases/download/v#{version}/digestive_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "235f8ca0a912cd858037aac9ed63ea9c5162499df7847de8a1a952dca086ce57"
      url "https://github.com/social-sync/digestive/releases/download/v#{version}/digestive_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "01f472ff0c5857b1fe01a343f426a2981ec81e8ea023aa9f5debca72ea947ddd"
      url "https://github.com/social-sync/digestive/releases/download/v#{version}/digestive_#{version}_linux_arm64.tar.gz"
    end
  end

  name "digestive"
  desc "Single-binary database exporter with anonymisation"
  homepage "https://github.com/social-sync/digestive"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "digestive"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/digestive"]
    end
  end

  # No zap stanza required

end
